"""Type definitions for gen_sql module."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class SqlCandidate:
    """
    Represents a single SQL query candidate generated by the LLM.
    
    Attributes:
        sql: The generated SQL query string
        expected_shape: Metadata about expected result shape
            - kind: "aggregation" | "list" | "scalar"
            - rows: "one" | "many" | "unknown"
        rationale: Optional explanation from LLM about query logic
        extra: Additional metadata (logprobs, prompt_id, raw_output, etc.)
    """
    sql: str
    expected_shape: Dict[str, Any] = field(default_factory=dict)
    rationale: Optional[str] = None
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GenerationResult:
    """
    Result of SQL generation process including validation status.
    
    Attributes:
        primary: The primary candidate to use for execution
        candidates: All generated candidates (k>=1)
        format_ok: Whether primary candidate passed basic format checks
        validation_errors: List of validation error messages
        debug_info: Additional debug information (prompts, raw outputs, etc.)
    """
    primary: SqlCandidate
    candidates: List[SqlCandidate] = field(default_factory=list)
    format_ok: bool = False
    validation_errors: List[str] = field(default_factory=list)
    debug_info: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GenerationSignals:
    """
    Numerical signals for Strategic Control Module (SCM).
    
    These signals help the SCM decide whether to:
    - Accept the generated SQL
    - Request regeneration
    - Apply format restrictions
    - Escalate to repair module
    
    Attributes:
        values: Dictionary of signal_name -> float_value
            Standard signals include:
            - num_candidates: number of SQL candidates generated
            - num_format_ok: how many passed format validation
            - primary_format_ok: 0.0 or 1.0
            - primary_sql_length_tokens: token count of primary SQL
            - has_group_by_without_agg: potential GROUP BY misuse
            - has_limit_clause: 0.0 or 1.0
            - risk_score: heuristic risk assessment [0.0, 1.0]
    """
    values: Dict[str, float] = field(default_factory=dict)
